web:
  upload-path :  D:\lib\web\mywebfront\MyWeb
  upload-path-pic :  D:\lib\web\mywebfront\MyWeb
spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

  ########################################################
  ### datasource
  ########################################################
  datasource:
    url: jdbc:mysql://localhost:3306/myweb
    username: root
    password: provinet433
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300
    mongodb:
      uri: mongodb://localhost:27017/spider

MAIN_WEB : myweb.html
LOGIN_WEB : login.html